export { default as ChevronDown } from "./chevron-down.svg";
export { default as Background } from "./background.svg";
export { default as BackgroundFull } from "./background-full.svg";
export { default as Logotype } from "./logotype.svg";
export { default as Github } from "./github.svg";
export { default as Linkedin } from "./linkedin.svg";
export { default as MenBlack } from "./men-black.svg";
export { default as Rectangle } from "./rectangle.svg";
export { default as Quotation } from "./quotation-marks.svg";
export { default as HandFace } from "./handonface.svg"
export { default as SiteImageOne } from "./siteimageone.svg"
export { default as SiteImageTwo } from "./siteimagetwo.svg"
export { default as SiteImageThree } from "./siteimagethree.svg"
export { default as SiteImageFour } from "./siteimagefour.svg"
export { ReactComponent as Burger } from "./chevron-open.svg"
export { ReactComponent as Closeburger } from "./chevron-close.svg"
export { default as Email } from "./email.svg"
export { default as Discord } from "./discord.svg"
export { default as SideSkills } from "./skillsside.svg"