export { default as Header } from "./header/";
export { default as Aside } from "./aside-media/";
export { default as Hero } from "./hero/";
export { default as Footer } from "./footer/";
export { default as Quote } from "./quote/"
export { default as AboutMe } from "./about-me"
export { default as Projects } from "./projects"
export { default as Contacts } from "./contacts"
export { default as Skills } from "./skills"